/**
 * Domain models for the Vuera eyewear platform.
 *
 * These types describe the core entities of the store. They are framework
 * agnostic and shared across the service layer, state stores, and UI.
 * Money values are integer cents (e.g. 18900 = $189.00) to avoid
 * floating-point rounding issues.
 */

export type UUID = string;

export type ISODateString = string;

/** Integer cents. */
export type Money = number;

export type UserRole = 'customer' | 'admin' | 'staff';

export type FrameShape = 'round' | 'square' | 'rectangular' | 'oval' | 'cat-eye' | 'aviator' | 'geometric';

export type FrameMaterial = 'acetate' | 'metal' | 'titanium' | 'mixed';

export type GenderTarget = 'unisex' | 'men' | 'women';

export type LensType = 'single-vision' | 'progressive' | 'reading' | 'non-prescription' | 'sunglasses';

export type ProductStatus = 'active' | 'draft' | 'archived';

export type ModerationStatus = 'pending' | 'approved' | 'rejected';

export interface ProductImage {
  id: UUID;
  productId: UUID;
  url: string;
  altText: string | null;
  /** Zero-based display order. */
  position: number;
  /** True when the image was generated by the AI try-on pipeline. */
  isAiGenerated: boolean;
}

export interface ProductVariant {
  id: UUID;
  productId: UUID;
  colorId: UUID | null;
  sizeId: UUID | null;
  /** e.g. "Matte Black / 52mm" */
  name: string;
  /** Lens tint for sunglasses, null for clear. */
  lensTint: string | null;
  priceCents: Money;
  /** Units available across all warehouses. */
  stock: number;
  sku: string;
}

export interface Product {
  id: UUID;
  slug: string;
  name: string;
  brandId: UUID | null;
  brandName: string | null;
  description: string | null;
  shapeId: UUID | null;
  shape: FrameShape | null;
  materialId: UUID | null;
  material: FrameMaterial | null;
  gender: GenderTarget;
  lensType: LensType;
  /** Base price in cents. */
  priceCents: Money;
  /** Compare-at price for sale display, null when not on sale. */
  compareAtPriceCents: Money | null;
  status: ProductStatus;
  /** Average rating 0–5, null before any reviews. */
  rating: number | null;
  reviewCount: number;
  /** Category slugs this product belongs to. */
  categorySlugs: string[];
  images: ProductImage[];
  variants: ProductVariant[];
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

export interface Category {
  id: UUID;
  slug: string;
  name: string;
  description: string | null;
  parentId: UUID | null;
}

export interface Brand {
  id: UUID;
  slug: string;
  name: string;
  description: string | null;
}

export interface Color {
  id: UUID;
  slug: string;
  name: string;
  hexCode: string | null;
}

export interface FrameShapeOption {
  id: UUID;
  slug: string;
  name: string;
}

export interface MaterialOption {
  id: UUID;
  slug: string;
  name: string;
}

export interface SizeOption {
  id: UUID;
  sizeMm: number;
  label: string;
}

export interface Review {
  id: UUID;
  productId: UUID;
  userId: UUID;
  authorName: string;
  rating: number;
  title: string;
  body: string;
  verifiedPurchase: boolean;
  moderationStatus: ModerationStatus;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

export interface CartItem {
  productId: UUID;
  variantId: UUID;
  name: string;
  image: string;
  unitPriceCents: Money;
  quantity: number;
}

export interface Cart {
  items: CartItem[];
  /** Subtotal before tax and shipping, in cents. */
  subtotalCents: Money;
  currency: string;
}

export interface Address {
  fullName: string;
  line1: string;
  line2: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  phone: string | null;
}

export type OrderStatus =
  | 'pending'
  | 'paid'
  | 'fulfilled'
  | 'shipped'
  | 'delivered'
  | 'cancelled'
  | 'refunded';

export interface OrderItem {
  id: UUID;
  orderId: UUID;
  productId: UUID | null;
  variantId: UUID | null;
  productName: string;
  variantName: string;
  unitPriceCents: Money;
  quantity: number;
}

export interface Order {
  id: UUID;
  userId: UUID;
  status: OrderStatus;
  subtotalCents: Money;
  shippingCents: Money;
  taxCents: Money;
  totalCents: Money;
  currency: string;
  shippingAddress: Address | null;
  items: OrderItem[];
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

export interface UserProfile {
  id: UUID;
  email: string;
  firstName: string | null;
  lastName: string | null;
  role: UserRole;
  avatarUrl: string | null;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

export interface FaceProfile {
  pupillaryDistanceMm: number;
  faceWidthMm: number;
  templeLengthMm: number;
}

export interface CustomerPreferences {
  id: UUID;
  userId: UUID;
  stylePrompt: string | null;
  budgetCents: Money | null;
  faceProfile: FaceProfile | null;
  preferredShapes: string[];
  preferredMaterials: string[];
  preferredColors: string[];
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/* ------------------------------------------------------------------ */
/* AI feature envelopes — placeholders for future pipelines.          */
/* ------------------------------------------------------------------ */

export interface VirtualTryOnRequest {
  productId: UUID;
  variantId: UUID;
  /** User-uploaded selfie URL or data URL. */
  sourceImageUrl: string;
}

export interface VirtualTryOnResult {
  id: UUID;
  productId: UUID;
  /** Resulting image with glasses composited onto the face. */
  resultImageUrl: string;
  /** Confidence score 0–1 from the fitting model. */
  fitConfidence: number;
  createdAt: ISODateString;
}

export interface RecommendationRequest {
  /** Free-text preferences from the user. */
  prompt: string;
  faceProfile: FaceProfile | null;
  budgetCents: Money | null;
  /** Category slugs to constrain the search. */
  categories: string[];
}

export interface RecommendationResult {
  productId: UUID;
  score: number;
  reason: string;
}
